### ISSUE TITLE
Segmentation fault attempt

### ISSUE THREAD

**Issue by ranpafin** [facile-it/paraunit#6] opened 2015-07-31 08:34 UTC
@fntlnz Do you know if **PHP7** and **HHVM** still output 

```
segmentation fault (core dumped)
```

In case of a segmentation fault?

For what i can see after commit  0dfc77babf24122b4a87503f4bb74dd2397a3f79 the output seem to be quite different.

HHVM:

```
Fatal error: String length exceeded 2^31-2: 18446744071626162096 in [...]
```

PHP7:

```
Fatal error: Out of memory (allocated 4194304) (tried to allocate 799999999999952 bytes) in [..]
```

**Comment by Jean85** [comment] 2015-07-31 08:40
That's because it's a fatal error and not a segfault.
Simply, HHVM and PHP7 have more protection in place, and it's harder to provoke a real segfault from code.

The extension that @fntlnz wrote causes a real segfault, so the output will completly depends on the env.

**Comment by fntlnz** [comment] 2015-07-31 08:44
I tried it on php 5.6.11 and 7.0.0beta2

**7.0.0beta2**
```
Segmentation fault (core dumped)
```

**5.6.11**
```
Segmentation fault (core dumped)
```

My extension does not compile on HHVM. If needed I can write a similar extension for that php implementation.

**Comment by ranpafin** [comment] 2015-07-31 08:53
@fntlnz I was under the impression we included the extension in our test case but for what i can see now here [SegFaultTestStub](https://github.com/facile-it/paraunit/blob/master/src/Paraunit/Tests/Stub/SegFaultTestStub.php#L5) we're still using the former version.

I'll make a try.

**Comment by fntlnz** [comment] 2015-07-31 09:17
I just added the extension, I have to edit the `SegFaultTestStub` to call `sigsegv()` and travis to load the extension.

**Comment by ranpafin** [comment] 2015-07-31 12:12
The build is now passing for PHP7.

@fntlnz  For HHVM it will output an incomplete test message.

**Comment by fntlnz** [comment] 2015-07-31 13:03
Yay!

**Comment by fntlnz** [comment] 2015-07-31 13:04
Shortly I'll add the HHVM extension

**Comment by ranpafin** [comment] 2015-08-04 08:51
@fntlnz i see the extension is now fully working for HHVM! I gueas we can close here :)

**Comment by Jean85** [comment] 2015-08-04 09:46
No it's not fixed yet! The build is green just because it's skipped for the missing extension ;)

**Comment by fntlnz** [comment] 2015-08-04 11:08
I wrote the hhvm extension this morning when I woke up :sleeping: and I haven't never build/tested it in fact is still in a branch. I have to build it locally and update travis then I'll merge to the master branch.

**Comment by ranpafin** [comment] 2015-08-04 13:02
@Jean85 @fntlnz ... I was looking at the bottom line, the green was phpsepc! Sorry :)

**Comment by Jean85** [comment] 2015-11-02 21:27
*ping* @fntlnz :ghost:

**Comment by Jean85** [comment] 2016-11-09 17:29
This is not going forward, as the issue is only on HHVM. The related test is now skipped there, closing.

**Closed by Jean85** 2016-11-09 17:29 UTC
