### ISSUE TITLE
Delete composer.phar

### ISSUE THREAD

**Issue by taueres** [facile-it/paraunit#10] opened 2015-09-11 10:45 UTC
The file composer.phar should not be part of the project. It's also quite bit ~1 MB.
I suggest to remote it and add a new .gitignore rule.

**Comment by fntlnz** [comment] 2015-09-12 15:14
Moreover travis download it at every build so this is definitely not needed in the project vcs.
Is a sin that now it's present in the history, so every clone will be affected by it's size.

**Comment by fntlnz** [comment] 2015-09-12 15:15
I'm opening a PR to remove this.

**Comment by fntlnz** [comment] 2015-09-12 15:17
Update: it was intended to be ignored, but it has been added to `.gitignore` before adding it to git.
https://github.com/facile-it/paraunit/blob/master/.gitignore#L6

**Comment by taueres** [comment] 2015-09-12 16:08
@fntlnz I bet you meant it has been added to .gitignore after adding to git. Isn't it?

**Comment by fntlnz** [comment] 2015-09-12 16:20
Yes

**Comment by Jean85** [comment] 2015-09-12 18:22
Fixed by 3d5d6c16, thanks @fntlnz

**Closed by Jean85** 2015-09-12 18:22 UTC
